/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"

extern void initialise_monitor_handles();
const uint32_t const_var = 100;
//Prototypes
void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);
void init_systic_timer(uint32_t tick_hz );
__attribute__((naked))void init_scheduler_stack(uint32_t sched_top_of_stack);
void init_tasks_stack(void);
void enable_processor_faults(void);
__attribute__((naked))void switch_sp_to_psp(void);
uint32_t get_psp_value(void);
void SysTick_Handler(void);
__attribute__((naked))void PendSV_Handler(void);
void update_next_task(void);
void save_psp_value(uint32_t current_psp_value);
void task_delay(uint32_t tick_count);
void unblock_tasks(void);
void schedule(void);

uint8_t current_task = 1; //Task-1 is running
uint32_t g_tick_count = 0;

typedef struct{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handler)(void);

}TCB_t;

TCB_t user_tasks[MAX_TASKS];
int main(void)
{

	

	enable_processor_faults();

	initialise_monitor_handles();

	init_scheduler_stack(SCHED_STACK_START); //Initialize MSP to the start of scheduler stack

	printf("Implementation of simple task Scheduler\n");
	init_tasks_stack();

	led_init_all();

	init_systic_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

	for(;;);
}

void idle_task(void){
	while(1);
}
void task1_handler(void){
	while(1){
		printf("In Task1\n");
		led_on(LED1);
		task_delay(1000);
		led_off(LED1);
		task_delay(1000);
	}
}
void task2_handler(void){
	while(1){
		printf("In Task2\n");
		led_on(LED2);
		task_delay(500);
		led_off(LED2);
		task_delay(500);
	}
}
void task3_handler(void){
	while(1){
		printf("In Task3\n");
		led_on(LED3);
		task_delay(250);
		led_off(LED3);
		task_delay(250);
	}
}
void task4_handler(void){
	while(1){
		printf("In Task4\n");
		led_on(LED4);
		task_delay(125);
		led_off(LED4);
		task_delay(125);
	}
}

void HardFault_Handler(void){
	printf("Exception : HardFault\n");
	while(1);
}

void MemManage_Handler(void){
	printf("Exception : MemManage\n");
	while(1);
}

void BusFault_Handler(void){
	printf("Exception : BusFault\n");
	while(1);
}

void UsageFault_Handler(void){
	printf("Exception : UsageFault\n");
	while(1);
}
void init_systic_timer(uint32_t tick_hz ){
	uint32_t *pSCSR = (uint32_t *)0xE000E010;
	uint32_t *pSRVR = (uint32_t *)0xE000E014;
	//Calculation of reload value
	uint32_t count_value = (SYSTICK_CLK_SOURCE/tick_hz) -1;
	//Loading the count value in the SYST_RVR register
	*pSRVR &= ~(0x00FFFFFFFF);
	*pSRVR |= count_value;

	//Enable the counter:
	*pSCSR |= (1 << 0);
	//Enable SYSTICk exception
	*pSCSR |= (1 << 1);
	//Select clock source as Processor Clock
	*pSCSR |= (1 << 2);
}

__attribute__((naked))void init_scheduler_stack(uint32_t sched_top_of_stack){
	__asm volatile("MSR MSP,%0" : : "r"(sched_top_of_stack));
	__asm volatile("BX LR");
}

void init_tasks_stack(void){

	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;

	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = idle_task;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	uint32_t *pPSP;
	for(int i = 0; i < MAX_TASKS; i++){
		pPSP = (uint32_t *)user_tasks[i].psp_value;
		pPSP--; //xPSR
		*pPSP = DUMMY_XPSR; //0x00100000

		pPSP--; //PC
		*pPSP = (uint32_t)user_tasks[i].task_handler;

		pPSP--; //LR
		*pPSP = 0xFFFFFFFD;

		//Initialize 0 for all the general purpose register
		for(int j = 0 ; j < 13 ; j++){
			pPSP--;
			*pPSP = 0;
		}

		user_tasks[i].psp_value = (uint32_t)pPSP; // now preserve the value of the pPSP

	}
}

void enable_processor_faults(void){
	uint32_t *pSHCRS = (uint32_t *)0xE000ED24;

	//Enable Usage Fault
	*pSHCRS |= (1 << 18);
	//Enable Bus Fault
	*pSHCRS |= (1 << 17);
	//Enable MemManage Fault
	*pSHCRS |= (1 << 16);
}

uint32_t get_psp_value(void){
	return user_tasks[current_task].psp_value;
}

__attribute__((naked))void switch_sp_to_psp(void){
	//1. Initialize the PSP to the Task-1 stack start address
	//push the actual value of LR which will get corrupted after the function call
	__asm volatile("PUSH {LR}");
	//Get the value of the current task
	__asm volatile("BL get_psp_value");
	//After the execution of get_psp_value initial stack address will be stored in R0
	__asm volatile("MSR PSP , R0"); // Initialized PSP
	__asm volatile("POP {LR}");

	//2.  Change SP to PSP using CONTROL register
	__asm volatile("MOV R0 , #0x02");
	__asm volatile("MSR CONTROL , R0");
	__asm volatile("BX LR");

}

void save_psp_value(uint32_t current_psp_value){
	user_tasks[current_task].psp_value = current_psp_value;
}

void update_next_task(void){
	int state = TASK_BLOCKED_STATE;

	for(int i = 0 ; i < MAX_TASKS ; i++){
		current_task = (current_task + 1) % MAX_TASKS;
		state = user_tasks[current_task].current_state;
		if((state == TASK_READY_STATE) && (current_task != 0)){
			break;
		}

	}
	if(state != TASK_READY_STATE){
		current_task = 0;
	}
}

void schedule(void){
	//Pend the PendSV Handler
	uint32_t *pICSR = (uint32_t *)0xE000ED04;
	*pICSR |= (1 << 28);
}



void task_delay(uint32_t tick_count){
	/*Disable interrupt to avoid race around condition in the chance
	 * that any interrupt and this function is accessing the same global memory at the same tiem
	 */
	INTERRUPT_DISABLE();

	if(current_task){
		user_tasks[current_task].block_count = g_tick_count + tick_count;
		user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
		schedule();
	}

	//Enable the Interrupts
	INTERRUPT_ENABLE();
}

void unblock_tasks(void)
{
    for(int i = 1; i < MAX_TASKS; i++)
    {
        if(user_tasks[i].current_state == TASK_BLOCKED_STATE)
        {
            if(user_tasks[i].block_count == g_tick_count)
            {
                user_tasks[i].current_state = TASK_READY_STATE;
            }
        }
    }
}
void SysTick_Handler(void){
	//Update Global Tick count
	g_tick_count++;

	unblock_tasks();

	//Pend the PendSV Handler
	uint32_t *pICSR = (uint32_t *)0xE000ED04;
	*pICSR |= (1 << 28);

}

__attribute__((naked))void PendSV_Handler(void){
	/************Save the context of the current task*************/

	//1. Get current running task's PSP value
	__asm volatile("MRS R0 , PSP");
	/*
	 * At this point stack frame of Task -1 looks like this
	 xPSR
	 PC
	 LR
	 R12
	 R3
	 R2
	 R1
	 R0 <-- PSP points here, and after MRS, CPU register R0 contains this address
	 */
	//2. Using the PSP value store SF2(R4 to R11)
	 __asm volatile("STMDB R0! , {R4-R11}");
	 //After this line stack frame of Task-1:-
	 /*
	  * Higher Address
		xPSR
		PC
		LR
		R12
		R3
		R2
		R1
		R0
		R11
		R10
		R9
		R8
		R7
		R6
		R5
		R4   <-- CPU register R0 contains this address now
		Lower Address
	  */
	//3. Save the current value of PSP
	 __asm volatile("PUSH {LR}");
	 __asm volatile("BL save_psp_value"); // When Function is branched it will pass the value in R0 as an arguement

	/***********Retrieve the Context of the next task************/

	 //1. Decide next task to run
	 __asm volatile("BL update_next_task");
	 //2. Get its past PSP value
	 __asm volatile("BL get_psp_value");

	 //Stack frame of Task-2 which is already saved:-
	 /*
	  * Higher Address
		xPSR
		PC
		LR
		R12
		R3
		R2
		R1
		R0
		R11
		R10
		R9
		R8
		R7
		R6
		R5
		R4   <-- CPU's R0 contains this address now
		Lower Address
	  */

	 //3. Using that PSP value restore SF2 (R4-R11)

	 __asm volatile("LDMIA R0! , {R4-R11}");
	 /*
	  * R4-R11 of Task-2 are now restored into the CPU registers.
	  *
	  * Due to the '!' write-back, R0 has been incremented
	  * and now points to the saved R0 of Task-2's hardware
	  * stack frame.
	  */

	 //4. Update PSP and exit
	 __asm volatile("MSR PSP , R0");
	 __asm volatile("POP {LR}");
	 __asm volatile("BX LR");

	 /*
	  * When the SysTick handler exits, the Cortex-M hardware performs exception return.
		The hardware automatically restores:
		R0
		R1
		R2
		R3
		R12
		LR
		PC
		xPSR
	  */
}
